/**
 *
 * @author Konrad Sautter
 */
public class impfenGUI extends javax.swing.JFrame {

    /**
     * Creates new form impfenGUI
     */
    public impfenGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        TabbedPane = new javax.swing.JTabbedPane();
        pImpfen = new javax.swing.JPanel();
        pKleinImpfen = new javax.swing.JPanel();
        tfImpfenImpfung = new javax.swing.JTextField();
        tfImpfenName = new javax.swing.JTextField();
        btImpfenImpfen = new javax.swing.JButton();
        scrpImpfen = new javax.swing.JScrollPane();
        epImpfenOUT = new javax.swing.JEditorPane();
        jLabel1 = new javax.swing.JLabel();
        pPatient = new javax.swing.JPanel();
        pSuchen = new javax.swing.JPanel();
        tfSuchenName = new javax.swing.JTextField();
        btSuchen = new javax.swing.JButton();
        scrpSuchen = new javax.swing.JScrollPane();
        epSuchenOUT = new javax.swing.JEditorPane();
        lbSuchen = new javax.swing.JLabel();
        pHinzufuegen = new javax.swing.JPanel();
        tfHzfName = new javax.swing.JTextField();
        tfHzfGeb = new javax.swing.JTextField();
        tfHzfGeschl = new javax.swing.JTextField();
        tfHzfAdr = new javax.swing.JTextField();
        tfHzfNum = new javax.swing.JTextField();
        btHzf = new javax.swing.JButton();
        scrpHzf = new javax.swing.JScrollPane();
        epHzfOUT = new javax.swing.JEditorPane();
        lbHinzufuegen = new javax.swing.JLabel();
        pDatenAendern = new javax.swing.JPanel();
        tfDatenZuAendern = new javax.swing.JTextField();
        tfDatenPatientName = new javax.swing.JTextField();
        tfDatenNeu = new javax.swing.JTextField();
        btDatenAendern = new javax.swing.JButton();
        scrpDaten = new javax.swing.JScrollPane();
        epDatenOUT = new javax.swing.JEditorPane();
        lbDaten = new javax.swing.JLabel();
        sbPatient = new javax.swing.JScrollBar();
        pLoeschen1 = new javax.swing.JPanel();
        tfLoeschenName = new javax.swing.JTextField();
        btLoeschen = new javax.swing.JButton();
        scrpLoeschen = new javax.swing.JScrollPane();
        epLoeschenOUT = new javax.swing.JEditorPane();
        lbLoeschen = new javax.swing.JLabel();
        pInformation = new javax.swing.JPanel();
        pStatus = new javax.swing.JPanel();
        tfStatusName = new javax.swing.JTextField();
        tfStatusImpfung = new javax.swing.JTextField();
        scrpStatus = new javax.swing.JScrollPane();
        epStatusOUT = new javax.swing.JEditorPane();
        btStatusAbfragen = new javax.swing.JButton();
        lbStatus = new javax.swing.JLabel();
        pAllgStat = new javax.swing.JPanel();
        tfAllgStatName = new javax.swing.JTextField();
        btAllgStat = new javax.swing.JButton();
        scrpAllgStat = new javax.swing.JScrollPane();
        epAllgStatOUT = new javax.swing.JEditorPane();
        lbInfo = new javax.swing.JLabel();
        pInfo = new javax.swing.JPanel();
        tfInfoName = new javax.swing.JTextField();
        tfInfoImpfung = new javax.swing.JTextField();
        btInfo = new javax.swing.JButton();
        scrpInfo = new javax.swing.JScrollPane();
        epInfoOUT = new javax.swing.JEditorPane();
        lbAllgStat = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TabbedPane.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N

        tfImpfenImpfung.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfImpfenImpfung.setForeground(new java.awt.Color(102, 102, 102));
        tfImpfenImpfung.setText("Impfung");
        tfImpfenImpfung.setPreferredSize(new java.awt.Dimension(100, 23));
        tfImpfenImpfung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfImpfenImpfungActionPerformed(evt);
            }
        });

        tfImpfenName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfImpfenName.setForeground(new java.awt.Color(102, 102, 102));
        tfImpfenName.setText("Name eingeben");
        tfImpfenName.setPreferredSize(new java.awt.Dimension(100, 23));
        tfImpfenName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfImpfenNameActionPerformed(evt);
            }
        });
        
        btImpfenImpfen.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btImpfenImpfen.setText("Impfen");
        btImpfenImpfen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImpfenImpfenActionPerformed(evt);
            }
        });

        scrpImpfen.setViewportView(epImpfenOUT);

        javax.swing.GroupLayout pKleinImpfenLayout = new javax.swing.GroupLayout(pKleinImpfen);
        pKleinImpfen.setLayout(pKleinImpfenLayout);
        pKleinImpfenLayout.setHorizontalGroup(
            pKleinImpfenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pKleinImpfenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pKleinImpfenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pKleinImpfenLayout.createSequentialGroup()
                        .addGroup(pKleinImpfenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfImpfenName, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                            .addComponent(tfImpfenImpfung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(66, 66, 66)
                        .addComponent(btImpfenImpfen, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scrpImpfen, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(397, Short.MAX_VALUE))
        );
        pKleinImpfenLayout.setVerticalGroup(
            pKleinImpfenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pKleinImpfenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pKleinImpfenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btImpfenImpfen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pKleinImpfenLayout.createSequentialGroup()
                        .addComponent(tfImpfenName, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                        .addGap(26, 26, 26)
                        .addComponent(tfImpfenImpfung, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(scrpImpfen, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Impfen");

        javax.swing.GroupLayout pImpfenLayout = new javax.swing.GroupLayout(pImpfen);
        pImpfen.setLayout(pImpfenLayout);
        pImpfenLayout.setHorizontalGroup(
            pImpfenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pImpfenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pKleinImpfen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pImpfenLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pImpfenLayout.setVerticalGroup(
            pImpfenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pImpfenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pKleinImpfen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(586, Short.MAX_VALUE))
        );

        TabbedPane.addTab("Impfen", pImpfen);

        tfSuchenName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfSuchenName.setForeground(new java.awt.Color(102, 102, 102));
        tfSuchenName.setText("Name eingeben\n");
        tfSuchenName.setPreferredSize(new java.awt.Dimension(100, 23));
        tfSuchenName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSuchenNameActionPerformed(evt);
            }
        });

        btSuchen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btSuchen.setText("Suchen");

        scrpSuchen.setViewportView(epSuchenOUT);

        lbSuchen.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbSuchen.setText("Suchen");

        javax.swing.GroupLayout pSuchenLayout = new javax.swing.GroupLayout(pSuchen);
        pSuchen.setLayout(pSuchenLayout);
        pSuchenLayout.setHorizontalGroup(
            pSuchenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSuchenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pSuchenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scrpSuchen, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pSuchenLayout.createSequentialGroup()
                        .addGroup(pSuchenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbSuchen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfSuchenName, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btSuchen, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pSuchenLayout.setVerticalGroup(
            pSuchenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSuchenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbSuchen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pSuchenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSuchenName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSuchen, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(scrpSuchen, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tfHzfName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfHzfName.setForeground(new java.awt.Color(102, 102, 102));
        tfHzfName.setText("Name eingeben");
        tfHzfName.setPreferredSize(new java.awt.Dimension(100, 23));
        tfHzfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfHzfNameActionPerformed(evt);
            }
        });

        tfHzfGeb.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfHzfGeb.setForeground(new java.awt.Color(102, 102, 102));
        tfHzfGeb.setText("Geburtstag");
        tfHzfGeb.setPreferredSize(new java.awt.Dimension(100, 23));

        tfHzfGeschl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfHzfGeschl.setForeground(new java.awt.Color(102, 102, 102));
        tfHzfGeschl.setText("Geschlecht");

        tfHzfAdr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfHzfAdr.setForeground(new java.awt.Color(102, 102, 102));
        tfHzfAdr.setText("Adresse");

        tfHzfNum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfHzfNum.setForeground(new java.awt.Color(102, 102, 102));
        tfHzfNum.setText("Telefonnummer");

        btHzf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btHzf.setText("Hinzufügen");

        scrpHzf.setViewportView(epHzfOUT);

        lbHinzufuegen.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbHinzufuegen.setText("Hinzufügen");

        javax.swing.GroupLayout pHinzufuegenLayout = new javax.swing.GroupLayout(pHinzufuegen);
        pHinzufuegen.setLayout(pHinzufuegenLayout);
        pHinzufuegenLayout.setHorizontalGroup(
            pHinzufuegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pHinzufuegenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pHinzufuegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbHinzufuegen, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addGroup(pHinzufuegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tfHzfName, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                        .addComponent(tfHzfGeb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfHzfGeschl)))
                .addGap(18, 18, 18)
                .addGroup(pHinzufuegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfHzfAdr)
                    .addComponent(tfHzfNum, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(btHzf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(scrpHzf, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pHinzufuegenLayout.setVerticalGroup(
            pHinzufuegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pHinzufuegenLayout.createSequentialGroup()
                .addComponent(lbHinzufuegen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pHinzufuegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfHzfName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfHzfAdr, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pHinzufuegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pHinzufuegenLayout.createSequentialGroup()
                        .addGroup(pHinzufuegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfHzfNum)
                            .addComponent(tfHzfGeb, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pHinzufuegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfHzfGeschl)
                            .addComponent(btHzf, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)))
                    .addComponent(scrpHzf))
                .addGap(21, 21, 21))
        );
        
        tfDatenZuAendern.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfDatenZuAendern.setForeground(new java.awt.Color(102, 102, 102));
        tfDatenZuAendern.setText("zu Ändernde Daten");

        tfDatenPatientName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfDatenPatientName.setForeground(new java.awt.Color(102, 102, 102));
        tfDatenPatientName.setText("Name Patient");

        tfDatenNeu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfDatenNeu.setForeground(new java.awt.Color(102, 102, 102));
        tfDatenNeu.setText("Neue Daten");

        btDatenAendern.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btDatenAendern.setText("Daten Ändern");
        btDatenAendern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDatenAendernActionPerformed(evt);
            }
        });

        scrpDaten.setViewportView(epDatenOUT);

        lbDaten.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbDaten.setText("Daten Ändern");

        javax.swing.GroupLayout pDatenAendernLayout = new javax.swing.GroupLayout(pDatenAendern);
        pDatenAendern.setLayout(pDatenAendernLayout);
        pDatenAendernLayout.setHorizontalGroup(
            pDatenAendernLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDatenAendernLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pDatenAendernLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lbDaten, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                    .addGroup(pDatenAendernLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(tfDatenZuAendern, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                        .addComponent(tfDatenPatientName, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tfDatenNeu)))
                .addGap(41, 41, 41)
                .addGroup(pDatenAendernLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrpDaten, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btDatenAendern, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(212, Short.MAX_VALUE))
        );
        pDatenAendernLayout.setVerticalGroup(
            pDatenAendernLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDatenAendernLayout.createSequentialGroup()
                .addComponent(lbDaten, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pDatenAendernLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pDatenAendernLayout.createSequentialGroup()
                        .addComponent(btDatenAendern, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(scrpDaten))
                    .addGroup(pDatenAendernLayout.createSequentialGroup()
                        .addComponent(tfDatenPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfDatenZuAendern, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfDatenNeu, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)))
                .addGap(23, 23, 23))
        );

        tfLoeschenName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfLoeschenName.setForeground(new java.awt.Color(102, 102, 102));
        tfLoeschenName.setText("Name eingeben\n");

        btLoeschen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btLoeschen.setText("Löschen");

        scrpLoeschen.setViewportView(epLoeschenOUT);

        lbLoeschen.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbLoeschen.setText("Löschen");

        javax.swing.GroupLayout pLoeschen1Layout = new javax.swing.GroupLayout(pLoeschen1);
        pLoeschen1.setLayout(pLoeschen1Layout);
        pLoeschen1Layout.setHorizontalGroup(
            pLoeschen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLoeschen1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pLoeschen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbLoeschen, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pLoeschen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(scrpLoeschen)
                        .addGroup(pLoeschen1Layout.createSequentialGroup()
                            .addComponent(tfLoeschenName, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(63, 63, 63)
                            .addComponent(btLoeschen, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pLoeschen1Layout.setVerticalGroup(
            pLoeschen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLoeschen1Layout.createSequentialGroup()
                .addComponent(lbLoeschen, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pLoeschen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfLoeschenName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLoeschen, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(scrpLoeschen, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pPatientLayout = new javax.swing.GroupLayout(pPatient);
        pPatient.setLayout(pPatientLayout);
        pPatientLayout.setHorizontalGroup(
            pPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPatientLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pHinzufuegen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pSuchen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pLoeschen1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pDatenAendern, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sbPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pPatientLayout.setVerticalGroup(
            pPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPatientLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pSuchen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pHinzufuegen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pLoeschen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pDatenAendern, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(sbPatient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        TabbedPane.addTab("Patient", pPatient);

        tfStatusName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfStatusName.setForeground(new java.awt.Color(102, 102, 102));
        tfStatusName.setText("Name eingeben");
        tfStatusName.setPreferredSize(new java.awt.Dimension(100, 23));

        tfStatusImpfung.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfStatusImpfung.setForeground(new java.awt.Color(102, 102, 102));
        tfStatusImpfung.setText("Impfung");
        tfStatusImpfung.setPreferredSize(new java.awt.Dimension(100, 23));
        tfStatusImpfung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfStatusImpfungActionPerformed(evt);
            }
        });

        scrpStatus.setViewportView(epStatusOUT);

        btStatusAbfragen.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btStatusAbfragen.setText("Abfragen");

        lbStatus.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbStatus.setText("Status");

        javax.swing.GroupLayout pStatusLayout = new javax.swing.GroupLayout(pStatus);
        pStatus.setLayout(pStatusLayout);
        pStatusLayout.setHorizontalGroup(
            pStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pStatusLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(scrpStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pStatusLayout.createSequentialGroup()
                            .addGroup(pStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfStatusImpfung, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfStatusName, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(68, 68, 68)
                            .addComponent(btStatusAbfragen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pStatusLayout.setVerticalGroup(
            pStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pStatusLayout.createSequentialGroup()
                .addComponent(lbStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pStatusLayout.createSequentialGroup()
                        .addComponent(tfStatusName, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfStatusImpfung, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btStatusAbfragen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(scrpStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        
        tfAllgStatName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfAllgStatName.setForeground(new java.awt.Color(102, 102, 102));
        tfAllgStatName.setText("Name eingeben");
        tfAllgStatName.setPreferredSize(new java.awt.Dimension(100, 23));

        btAllgStat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btAllgStat.setText("Abfragen");

        scrpAllgStat.setViewportView(epAllgStatOUT);

        lbInfo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbInfo.setText("Information");

        javax.swing.GroupLayout pAllgStatLayout = new javax.swing.GroupLayout(pAllgStat);
        pAllgStat.setLayout(pAllgStatLayout);
        pAllgStatLayout.setHorizontalGroup(
            pAllgStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAllgStatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pAllgStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lbInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addGroup(pAllgStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tfAllgStatName, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                        .addComponent(btAllgStat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(55, 55, 55)
                .addComponent(scrpAllgStat, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        pAllgStatLayout.setVerticalGroup(
            pAllgStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pAllgStatLayout.createSequentialGroup()
                .addComponent(lbInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pAllgStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrpAllgStat, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pAllgStatLayout.createSequentialGroup()
                        .addComponent(tfAllgStatName, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btAllgStat, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        tfInfoName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfInfoName.setForeground(new java.awt.Color(102, 102, 102));
        tfInfoName.setText("Name eingeben");
        tfInfoName.setPreferredSize(new java.awt.Dimension(100, 23));

        tfInfoImpfung.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfInfoImpfung.setForeground(new java.awt.Color(102, 102, 102));
        tfInfoImpfung.setText("Impfung");
        tfInfoImpfung.setPreferredSize(new java.awt.Dimension(100, 23));
        tfInfoImpfung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfInfoImpfungActionPerformed(evt);
            }
        });

        btInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btInfo.setText("Suchen");

        scrpInfo.setViewportView(epInfoOUT);

        lbAllgStat.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbAllgStat.setText("Allgemeiner Status");

        javax.swing.GroupLayout pInfoLayout = new javax.swing.GroupLayout(pInfo);
        pInfo.setLayout(pInfoLayout);
        pInfoLayout.setHorizontalGroup(
            pInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pInfoLayout.createSequentialGroup()
                        .addComponent(lbAllgStat, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pInfoLayout.createSequentialGroup()
                        .addGroup(pInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pInfoLayout.createSequentialGroup()
                                .addComponent(tfInfoName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(56, 56, 56))
                            .addGroup(pInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfInfoImpfung, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(scrpInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pInfoLayout.setVerticalGroup(
            pInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pInfoLayout.createSequentialGroup()
                .addComponent(lbAllgStat, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scrpInfo)
                    .addGroup(pInfoLayout.createSequentialGroup()
                        .addComponent(tfInfoName, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfInfoImpfung, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        
        javax.swing.GroupLayout pInformationLayout = new javax.swing.GroupLayout(pInformation);
        pInformation.setLayout(pInformationLayout);
        pInformationLayout.setHorizontalGroup(
            pInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pInformationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pAllgStat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pInformationLayout.setVerticalGroup(
            pInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInformationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pAllgStat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        TabbedPane.addTab("Information", pInformation);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 887, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbedPane)
        );

        pack();
    }// </editor-fold>                        

       private void tfStatusImpfungActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    private void tfInfoImpfungActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void tfImpfenNameActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void tfImpfenImpfungActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    private void tfSuchenNameActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void tfHzfNameActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void btImpfenImpfenActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void btDatenAendernActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void btStatusAbfragenActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    }                                                

    private void tfStatusNameActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void tfAllgStatNameActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void btAllgStatActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void tfInfoNameActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void btInfoActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void btSuchenActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void tfHzfGebActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void tfHzfGeschlActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void tfHzfAdrActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void tfHzfNumActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void btHzfActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void tfLoeschenNameActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void btLoeschenActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void tfDatenPatientNameActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
    }                                                  

    private void tfDatenZuAendernActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    }                                                

    private void tfDatenNeuActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(impfenGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(impfenGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(impfenGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(impfenGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new impfenGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTabbedPane TabbedPane;
    private javax.swing.JButton btAllgStat;
    private javax.swing.JButton btDatenAendern;
    private javax.swing.JButton btHzf;
    private javax.swing.JButton btImpfenImpfen;
    private javax.swing.JButton btInfo;
    private javax.swing.JButton btLoeschen;
    private javax.swing.JButton btStatusAbfragen;
    private javax.swing.JButton btSuchen;
    private javax.swing.JEditorPane epAllgStatOUT;
    private javax.swing.JEditorPane epDatenOUT;
    private javax.swing.JEditorPane epHzfOUT;
    private javax.swing.JEditorPane epImpfenOUT;
    private javax.swing.JEditorPane epInfoOUT;
    private javax.swing.JEditorPane epLoeschenOUT;
    private javax.swing.JEditorPane epStatusOUT;
    private javax.swing.JEditorPane epSuchenOUT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbAllgStat;
    private javax.swing.JLabel lbDaten;
    private javax.swing.JLabel lbHinzufuegen;
    private javax.swing.JLabel lbInfo;
    private javax.swing.JLabel lbLoeschen;
    private javax.swing.JLabel lbStatus;
    private javax.swing.JLabel lbSuchen;
    private javax.swing.JPanel pAllgStat;
    private javax.swing.JPanel pDatenAendern;
    private javax.swing.JPanel pHinzufuegen;
    private javax.swing.JPanel pImpfen;
    private javax.swing.JPanel pInfo;
    private javax.swing.JPanel pInformation;
    private javax.swing.JPanel pKleinImpfen;
    private javax.swing.JPanel pLoeschen1;
    private javax.swing.JPanel pPatient;
    private javax.swing.JPanel pStatus;
    private javax.swing.JPanel pSuchen;
    private javax.swing.JScrollBar sbPatient;
    private javax.swing.JScrollPane scrpAllgStat;
    private javax.swing.JScrollPane scrpDaten;
    private javax.swing.JScrollPane scrpHzf;
    private javax.swing.JScrollPane scrpImpfen;
    private javax.swing.JScrollPane scrpInfo;
    private javax.swing.JScrollPane scrpLoeschen;
    private javax.swing.JScrollPane scrpStatus;
    private javax.swing.JScrollPane scrpSuchen;
    private javax.swing.JTextField tfAllgStatName;
    private javax.swing.JTextField tfDatenNeu;
    private javax.swing.JTextField tfDatenPatientName;
    private javax.swing.JTextField tfDatenZuAendern;
    private javax.swing.JTextField tfHzfAdr;
    private javax.swing.JTextField tfHzfGeb;
    private javax.swing.JTextField tfHzfGeschl;
    private javax.swing.JTextField tfHzfName;
    private javax.swing.JTextField tfHzfNum;
    private javax.swing.JTextField tfImpfenImpfung;
    private javax.swing.JTextField tfImpfenName;
    private javax.swing.JTextField tfInfoImpfung;
    private javax.swing.JTextField tfInfoName;
    private javax.swing.JTextField tfLoeschenName;
    private javax.swing.JTextField tfStatusImpfung;
    private javax.swing.JTextField tfStatusName;
    private javax.swing.JTextField tfSuchenName;
    // End of variables declaration                   
}

